title: "Yashwanth Atla"
description: "Learning Transformers and RLHF from scratch"
author: "Yashwanth Atla"
email: "yashwanthatla1431@gmail.com"
github_username: yashuatla1431
theme: minima

show_excerpts: true
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag